version: '3.9'

services:
  # backend service
  webguia-backend:
    build: .
    restart: always
    container_name: webguia-backend
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - webguia-db
    environment:
      DATABASE: ${DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
      DB_HOST : webguia-db
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_EXPIRES: ${AUTH_EXPIRES}
      AUTH_ROUNDS: ${AUTH_EXPIRES}
  webguia-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - ${DB_HOST}:3306 
    volumes:
      - ./db:/var/lib/mysql